# work in progress
# use https://editor.swagger.io/ to edit this file
openapi: 3.0.2
info:
  title: gotenberg
  description: >-
    Gotenberg is a Docker-powered stateless API for converting HTML, Markdown,
    SVG and Office documents to PDF.
  version: ''
paths:
  /convert/office:
    post:
      tags: []
      summary: Convert Office file
      description: |
        Gotenberg provides the endpoint /convert/office for Office document conversions.
        It accepts POST requests with a multipart/form-data Content-Type.
      requestBody:
        content:
          multipart/form-data:
            schema:
              required:
                - files
              type: object
              properties:
                files:
                  type: string
                  format: binary
                pageRanges:
                  type: string
        required: true
      responses:
        '200':
          description: Successful Response
  /merge:
    post:
      tags: []
      summary: Merging PDF
      description: |
        Gotenberg provides the endpoint /merge for merging PDFs.
        It accepts POST requests with a multipart/form-data Content-Type.
      requestBody:
        content:
          multipart/form-data:
            schema:
              required:
                - files
              type: object
              properties:
                files:
                  description: some description
                  type: array
                  items:
                    type: string
                    format: binary
                waitTimeout:
                  type: number
                webhookURL:
                  type: string
                webhookURLTimeout:
                  type: string

        required: true
      responses:
        '200':
          description: Successful Response
  /convert/inkscape:
    post:
      tags: []
      summary: Convert SVG to PDF
      description: |
        Convert a SVG file to a PDF file with Inkscape.
      requestBody:
        content:
          multipart/form-data:
            schema:
              required:
                - files
              type: object
              properties:
                files:
                  type: string
                  format: binary
                waitTimeout:
                  type: number
                webhookURL:
                  type: string
                webhookURLTimeout:
                  type: string

        required: true
      responses:
        '200':
          description: Successful Response          